### ISSUE TITLE
Broken links on Collaborators page

### ISSUE THREAD

**Issue by latmarat** [mined-gatech/mined-gatech.github.io#4]
Links to [Dr. Rollett](http://www.materials.cmu.edu/people/rollett.html) and [Dr. Tasan](http://www.mpie.de/2973988/employee_page?c=3079071&employee_id=40045) lead to non-existing pages.

Correct links:
Dr. Rollett - http://www.cmu.edu/engineering/materials/people/faculty/bios/rollett.html
Dr. Tasan - http://www.mpie.de/2973988/employee_page?c=2768971&employee_id=43181

Also, there seems to be a typo in Dr. Rollett's name: Antony -> Anthony.

**Comment by ahmetcecen** [comment]
Will fix, thanks.

**Comment by fredhohman** [comment]
Fixed.
